command:
  remote-write:
    exit-status: 0
    exec: |
      LABEL_NAME="testlabel"
      LABEL_VALUE_1="otelcol"
      LABEL_VALUE_2="nodeexporter"
      # Check there is a LABEL_NAME label with value LABEL_VALUE_x
      LABELS="$(curl -s "localhost:9090/api/v1/label/${LABEL_NAME}/values")"
      echo "Prometheus '${LABEL_NAME}' label values: $LABELS"
      if ! echo "$LABELS" | grep -q "${LABEL_VALUE_1}"; then
        echo "'${LABEL_NAME}=${LABEL_VALUE_1}' label not found"
        exit 2
      fi
      if ! echo "$LABELS" | grep -q "${LABEL_VALUE_2}"; then
        echo "'${LABEL_NAME}=${LABEL_VALUE_2}' label not found"
        exit 3
      fi
