summary: Run prometheus-integration test

execute: |
  PROJECT="otelcol-prometheus-integration-test"

  # Deploy the test stack
  docker compose --project-name "$PROJECT" up --detach

  # Wait for the containers to settle and otel-collector to remote-write
  sleep 15

  goss \
    --gossfile goss.yaml \
    --log-level debug \
    validate \
    --retry-timeout=120s \
    --sleep=5s

restore: |
  PROJECT="otelcol-prometheus-integration-test"

  docker compose --project-name "$PROJECT" down --volumes
